# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.dinosauria.net:587
mail_admin: hello@dinosauria.net
mail_hostname: dinosauria.net
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
