name: trellis-cli & PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: cd site && composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Roots - Setup trellis-cli
      # You may pin to the exact commit or the version.
      # uses: roots/setup-trellis-cli@917fd0e4aa272d0aad42410455062f0ebff1d653
      uses: roots/setup-trellis-cli@v1.2.0
      with:
        # Whether to automatically run the `init` command after install (default: true).
        auto-init: true
        # Ansible Vault password (use a GitHub secret for this value). If you do not use Vault, set a placeholder string value anyway.
        ansible-vault-password: uh
        # Caches the trellis-cli managed virtualenv (default: true).
        cache-virtualenv: true
        # Whether to automatically run `trellis galaxy install` (default: true).
        galaxy-install: true
        # GitHub repository access token used for API authentication. Set this to avoid API rate limits.
        # repo-token: # optional
        # Path to Trellis project directory
        trellis-directory: trellis
        # Version of Trellis CLI to install
        version: latest
        
    - name: Trellis Deploy
      # You may pin to the exact commit or the version.
      # uses: steenbergen-design/trellis-action@0dc485d7dcf4816dfa3a978650776b7428a3583a
      uses: steenbergen-design/trellis-action@v1.0.2
      with:
        # galaxy role file containing a list of roles to be imported
        #role_file: # optional, default is galaxy.yml
        # ansible vault password
        #vault_password: # optional
        # ansible vault password file to use. Must be the same one in ansible.cfg(if applicable)
        #vault_password_file: # optional, default is .vault_pass
        # the environment to deploy to (staging, production, etc)
        site_env: production
        # the WordPress site to deploy (name defined in wordpress_sites)
        #site_name: # optional
        # Search the WordPress site by key == value
        site_key: dinosauria.net
        # Search the WordPress site by key == value
        #site_value: # optional
        # Path where site lives
        #site_path: # optional, default is ${{ github.workspace }}
        # Path where trellis lives
        #trellis_path: # optional, default is ${{ github.workspace }}/trellis
        # Group vars where sites are defined.
        #group_vars: # optional
        # 
        verbose: true
        # Ansible strategy to use, supports mitogen.
        #ansible_strategy: # optional, default is linear
        # Yarn cache path, used for caching the cache.
        #yarn_cache: # optional, default is ${{ github.workspace }}/.cache/yarn
