name: trellis-cli & PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: cd site && composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Roots - Setup trellis-cli
      # You may pin to the exact commit or the version.
      # uses: roots/setup-trellis-cli@917fd0e4aa272d0aad42410455062f0ebff1d653
      uses: roots/setup-trellis-cli@v1.2.0
      with:
        # Whether to automatically run the `init` command after install (default: true).
        auto-init: true
        # Ansible Vault password (use a GitHub secret for this value). If you do not use Vault, set a placeholder string value anyway.
        ansible-vault-password: uh
        # Caches the trellis-cli managed virtualenv (default: true).
        cache-virtualenv: true
        # Whether to automatically run `trellis galaxy install` (default: true).
        galaxy-install: true
        # GitHub repository access token used for API authentication. Set this to avoid API rate limits.
        # repo-token: # optional
        # Path to Trellis project directory
        trellis-directory: trellis
        # Version of Trellis CLI to install
        version: latest
